# Configuração básica do NGINX
worker_processes auto;
events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        listen 443 ssl;
        
        # Certificados SSL (substitua pelos caminhos reais dos certificados)
        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;
        
        # Configuração de redirecionamento HTTP -> HTTPS
        # if ($scheme = http) {
        #     return 301 https://$host$request_uri;
        # }

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
    }
}
